Repository aristanetworks/anta, pull requests merged in 2023-08, with the labels that each got.

#322 doc: Add note for manual release of a package
  .github/release.md
Labels: documentation, CI

#325 bump: update dependencies version in loose requirements
  pyproject.toml
Labels: dependencies

#327 ci: Update workflows for new features
  .github/workflows/code-testing.yml
  .github/workflows/pr-triage.yml
Labels: CI

#328 fix: aaa configuration check in `anta exec collect-tech-support`
  anta/cli/exec/utils.py
  docs/cli/exec.md
Labels: bug

#337 ci: Add comment if docs/ is not updated
  .github/workflows/code-testing.yml
Labels: CI

#338 fix(anta): Remove paswsord field in get inventory and debug
  anta/device.py
Labels: framework-enhancement

#340 feat: prompt passwords from stdin if not provided via CLI options
  anta/cli/__init__.py
  anta/cli/utils.py
  docs/README.md
  docs/snippets/anta_help.txt
Labels: Anta CLI

#346 feat(anta.tests): Add new interfaces.VerifyL2MTU test
  anta/tests/interfaces.py
  examples/tests.yaml
  tests/units/anta_tests/interfaces/data.py
  tests/units/anta_tests/interfaces/test_exc.py
Labels: network-tests

#345 fix(anta.tests): Add support for more options in VerifyL3MTU
  anta/tests/interfaces.py
  examples/tests.yaml
  tests/units/anta_tests/interfaces/data.py
  tests/units/anta_tests/interfaces/test_exc.py
Labels: network-tests

#350 fix(anta.tests): Update VerifyCoredump to JSON output and skip minidump folder
  anta/tests/system.py
  tests/units/anta_tests/system/data.py
Labels: network-tests

#348 fix(anta.tests): Update VerifyInterfaceErrors test with proper results
  anta/tests/interfaces.py
  tests/units/anta_tests/interfaces/data.py
Labels: network-tests

#349 doc: Implement UML diagram for classes
  docs/api/device.md
  docs/api/models.md
  docs/api/result_manager.md
  docs/api/result_manager_models.md
  docs/contribution.md
  docs/imgs/uml/anta.device.AntaDevice.jpeg
  docs/imgs/uml/anta.device.AsyncEOSDevice.jpeg
  docs/imgs/uml/anta.models.AntaCommand.jpeg
  docs/imgs/uml/anta.models.AntaTemplate.jpeg
  docs/imgs/uml/anta.models.AntaTest.jpeg
  docs/imgs/uml/anta.result_manager.ResultManager.jpeg
  docs/imgs/uml/anta.result_manager.models.TestResult.jpeg
Labels: documentation

#351 fix(anta.tests): Update STP AntaTemplate tests
  anta/tests/stp.py
  tests/units/anta_tests/interfaces/data.py
  tests/units/anta_tests/stp/data.py
Labels: network-tests

#353 ci: Update workflow for comment if docs/ is not updated
  .github/workflows/code-testing.yml
Labels: CI

#357 doc: Added FAQ page + note about urllib3
  docs/faq.md
  docs/requirements-and-installation.md
  mkdocs.yml
Labels: documentation

#359 ci: Update release workflow to link jobs
  .github/workflows/on-demand.yml
  .github/workflows/release.yml
Labels: CI

#364 doc: Add demo link to README
  docs/README.md
Labels: documentation

#365 doc: Add badge for repo activity
  docs/README.md
Labels: documentation
