Repository aristanetworks/anta, pull requests merged in 2023-06, with the labels that each got.

#204 doc: Update test syntax in ResultManager docstring
  anta/result_manager/__init__.py
Labels: documentation

#205 fix(anta): Added minor stuff for AVD integration
  anta/models.py
  anta/result_manager/models.py
  anta/tools/pydantic.py
  docs/api/tests.logging.md
Labels: documentation, framework-enhancement

#209 fix(anta.cli): Update exec snapshot to support no enable-password
  .gitignore
  anta/cli/exec/utils.py
  anta/result_manager/models.py
Labels: bug

#197 feat(anta): Implement Result manager for Jinja2 rendering
  anta/cli/check/commands.py
  anta/cli/check/utils.py
  anta/cli/cli.py
  anta/reporter/__init__.py
  anta/result_manager/__init__.py
  docs/cli/nrfu.md
  pyproject.toml
Labels: framework-enhancement, Anta CLI

#214 feat(anta.cli): added latest option to collect-tech-support
  anta/cli/exec/commands.py
  anta/cli/exec/utils.py
  docs/cli/exec.md
Labels: framework-enhancement, Anta CLI

#213 feat(anta): Enable support for AntaTestTemplate
  anta/cli/check/commands.py
  anta/cli/utils.py
  anta/runner.py
  docs/usage-inventory-catalog.md
Labels: framework-enhancement
