Repository aristanetworks/anta, pull requests merged in 2023-03, with the labels that each got.

#145 fix: Add missing sub-module in pyproject
  pyproject.toml
Labels: bug

#146 Chore: Make packages detection automatic
  pyproject.toml
Labels: bug

#143 doc: Update to show anta installation with pip
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/contribution.md
  docs/getting-started.md
  docs/requirements-and-installation.md
Labels: documentation

#147 fix(anta): Support for implicit default tag when not set by user
  anta/cli/check/commands.py
  anta/cli/check/utils.py
  anta/cli/cli.py
  anta/cli/get/__init__.py
  anta/cli/get/commands.py
  anta/cli/get/utils.py
  anta/cli/inventory/commands.py
  anta/inventory/__init__.py
  anta/inventory/models.py
  anta/tests/configuration.py
  docs/usage-anta-cli.md
Labels: framework-enhancement

#150 doc: Update structure & Add new commands
  docs/README.md
  docs/cli/exec.md
  docs/cli/get-inventory-information.md
  docs/cli/inv-from-cvp.md
  docs/cli/nrfu.md
  docs/cli/overview.md
  docs/usage-anta-cli.md
  mkdocs.yml
Labels: documentation

#148 fix(anta.tests): Allow verify_running_config to support no enable pasword
  anta/tests/configuration.py
  tests/units/test_tests/test_configuration.py
Labels: bug, network-tests

#149 feat(anta.cli): Implement exec tech-support to replace script
  .gitignore
  anta/cli/cli.py
  anta/cli/exec/commands.py
  anta/cli/exec/utils.py
  anta/inventory/models.py
Labels: Anta CLI

#154 doc: Add cli exec collect-tech-support command doc
  docs/cli/exec.md
Labels: documentation, Anta CLI

#155 revert(anta.cli): Add ascii art for anta --version
  anta/cli/cli.py
  anta/cli/utils.py
Labels: bug, Anta CLI
