Repository aristanetworks/anta, pull requests merged in 2024-06, with the labels that each got.

#691 chore: ownership updates and repository move to aristanetworks
  .devcontainer/devcontainer.json
  .pre-commit-config.yaml
  .vscode/settings.json
  Dockerfile
  docs/README.md
  docs/scripts/generate_svg.py
  examples/README.md
  mkdocs.yml
  pyproject.toml
Labels: documentation

#678 feat(anta.tests): Add testcases for ISIS SR Adjascency Segments
  anta/tests/routing/isis.py
  docs/stylesheets/extra.material.css
  docs/usage-inventory-catalog.md
  pyproject.toml
  tests/conftest.py
  tests/units/anta_tests/routing/test_isis.py
Labels: network-tests

#698 doc: Update all references to old GH org
  .github/release.md
  Dockerfile
  anta/__init__.py
  anta/cli/debug/utils.py
  docs/README.md
  docs/contribution.md
  docs/faq.md
  docs/requirements-and-installation.md
  docs/troubleshooting.md
  docs/usage-inventory-catalog.md
Labels: documentation

#700 feat(anta.cli): Make CV certs verified by default
  anta/cli/get/commands.py
  anta/cli/get/utils.py
  anta/inventory/models.py
  docs/cli/inv-from-cvp.md
  tests/units/cli/get/test_commands.py
  tests/units/cli/get/test_utils.py
Labels: framework-enhancement

#702 doc: Use lightbox JS for images
  docs/README.md
  docs/advanced_usages/custom-tests.md
  docs/cli/nrfu.md
  docs/usage-inventory-catalog.md
  mkdocs.yml
  pyproject.toml
Labels: documentation

#703 doc: Address recommendations and issues from doc review
  docs/README.md
  docs/getting-started.md
  docs/troubleshooting.md
Labels: documentation

#725 doc: Remove moving banner from doc
  docs/overrides/main.html
Labels: documentation
