Repository aristanetworks/anta, pull requests merged in 2024-02, with the labels that each got.

#517 feat(anta.tests): Add LANZ, PTP and GreenT
  anta/tests/greent.py
  anta/tests/lanz.py
  anta/tests/ptp.py
  tests/units/anta_tests/test_greent.py
  tests/units/anta_tests/test_lanz.py
  tests/units/anta_tests/test_ptp.py
Labels: network-tests

#530 fix(anta.cli): Allow commands in snapshot to use / and protect filename
  anta/cli/exec/utils.py
Labels: Anta CLI

#495 feat(anta.tests): Adding the test case to verify BGP neighbor authentication
  anta/tests/routing/bgp.py
  examples/tests.yaml
  tests/units/anta_tests/routing/test_bgp.py
Labels: one-more-review

#500 feat(anta.tests): Adding the test case to verify BFD session and timers
  anta/custom_types.py
  anta/tests/bfd.py
  examples/tests.yaml
  tests/units/anta_tests/test_bfd.py
Labels: one-more-review

#519 feat(anta.tests): New BGP EVPN Type-2 route test
  anta/tests/routing/bgp.py
  examples/tests.yaml
  pyproject.toml
  tests/units/anta_tests/routing/test_bgp.py
Labels: validated

#501 feat(anta.tests): Adding the test case to verify BGP advertised community
  anta/tests/routing/bgp.py
  examples/tests.yaml
  tests/units/anta_tests/routing/test_bgp.py
Labels: validated

#510 feat(anta.tests): Adding the test case to verify BGP timers
  anta/tests/routing/bgp.py
  examples/tests.yaml
  tests/units/anta_tests/routing/test_bgp.py
Labels: validated
